frr defaults datacenter
hostname spine1

interface lo
 ip address 10.255.0.1/32

interface eth1
 description "TO_LEAF1_ETH1"
 ip address 10.0.0.0/31

interface eth2
 description "TO_LEAF2_ETH1"
 ip address 10.0.0.2/31

router bgp 65001
 bgp router-id 10.255.0.1
 no bgp ebgp-requires-policy
 neighbor 10.0.0.1 remote-as 65011
 neighbor 10.0.0.1 description leaf1
 neighbor 10.0.0.3 remote-as 65012
 neighbor 10.0.0.3 description leaf2
 !
 address-family ipv4 unicast
  network 10.255.0.1/32
  neighbor 10.0.0.1 activate
  neighbor 10.0.0.3 activate
 exit-address-family
