frr defaults datacenter
hostname spine2

interface lo
 ip address 10.255.0.2

interface eth1
 description "TO_LEAF1_ETH2"
 ip address 10.0.0.4/31

interface eth2
 description "TO_LEAF2_ETH2"
 ip address 10.0.0.6/31
    
router bgp 65002
 bgp router-id 10.255.0.2
 no bgp ebgp-requires-policy
 neighbor 10.0.0.5 remote-as 65011
 neighbor 10.0.0.5 description leaf1
 neighbor 10.0.0.7 remote-as 65012
 neighbor 10.0.0.7 description leaf2
 !
 address-family ipv4 unicast
  network 10.255.0.2/32
  neighbor 10.0.0.5 activate
  neighbor 10.0.0.7 activate
 exit-address-family
